version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    image: car_sharing_app
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "bot.username" : "$BOT_USERNAME",
        "bot.token" : "$BOT_TOKEN",
        "bot.target-chat-id" : "$BOT_TARGET_CHAT_ID",
        "stripe.public.key" : "$STRIPE_PUBLIC_KEY",
        "stripe.secret.key" : "$STRIPE_SECRET_KEY",
        "stripe.success.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/success?rentalId=",
        "stripe.cancel.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/cancel?rentalId="
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
